---
name: Black Code Formatter

on:
  push:
    branches: [main, refactor-codebase]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Black
        run: pip install black==22.3.0
      - name: Display Black version
        run: black --version
      - name: Run Black
        run: python scripts/run_black.py
      - name: Check for changes
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "Black made changes. Please commit these changes."
            git diff
            exit 1
          else
            echo "No changes made by Black."
          fi
