name: Black Code Formatter

on:
  push:
    branches: [ main, refactor-codebase ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Black
        run: pip install black==22.3.0
      - name: Run Black
        run: black --check --verbose --line-length 100 ./src
      - name: If needed, apply Black formatting
        if: failure()
        run: |
          black --line-length 100 ./src
      - name: Commit changes
        run: |
          git config --global user.name github-actions
          git config --global user.email '${GITHUB_ACTOR}@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git diff --quiet && git diff --staged --quiet || (git commit -am "Automated code formatting with Black" && git push)
